import unittest
from commands import *
from vocab import Vocab

# English words will never exist in the real data. I'm taking
# advantage of that, and that 送る has one reading, to allow
# the tests to expect things not to exist, or that make
# modifications to not rely on the existing data.


class CommandsTestCase(unittest.TestCase):

    def setUp(self):
        self.vocab = Vocab('vocab.csv')
        self.commandStack = CommandStack()

    def test_NewCommand(self):
        self.assertEqual(self.commandStack.current(), -1)
        command = AddCommand(self.vocab, 'new')
        self.commandStack.do(command)
        self.assertEqual(self.commandStack.current(), 0)
        self.assertTrue(self.vocab.contains('new'))
        message = self.commandStack.undo()
        self.assertEqual(
            message, 'newはリスト%sから削除した。' %
            self.vocab.new_kanji_list_name())
        self.assertEqual(self.commandStack.current(), -1)
        self.assertFalse(self.vocab.contains('new'))
        message = self.commandStack.redo()
        self.assertEqual(
            message, 'newはリスト%sに追加した。' %
            self.vocab.new_kanji_list_name())
        self.assertEqual(self.commandStack.current(), 0)
        self.assertTrue(self.vocab.contains('new'))
        self.commandStack.undo()
        self.assertEqual(self.commandStack.current(), -1)
        self.assertFalse(self.vocab.contains('new'))

    def test_DeleteCommand(self):
        self.assertEqual(self.commandStack.current(), -1)
        self.vocab.toggle_known('送る')
        self.vocab.new_kana('送る', 'new')
        list_name = self.vocab.get_list_name('送る')
        known = self.vocab.get_known('送る')
        kana = self.vocab.get_kana('送る')
        command = DeleteCommand(self.vocab, '送る')
        self.commandStack.do(command)
        self.assertEqual(self.commandStack.current(), 0)
        self.assertFalse(self.vocab.contains('送る'))
        message = self.commandStack.undo()
        self.assertEqual(message, '送るはリスト0100に追加した。')
        self.assertEqual(self.commandStack.current(), -1)
        self.assertTrue(self.vocab.contains('送る'))
        self.assertEqual(self.vocab.get_list_name('送る'), list_name)
        self.assertEqual(self.vocab.get_known('送る'), known)
        self.assertEqual(self.vocab.get_kana('送る'), kana)
        message = self.commandStack.redo()
        self.assertEqual(message, '送るはリスト0100から削除した。')
        self.assertEqual(self.commandStack.current(), 0)
        self.assertFalse(self.vocab.contains('送る'))
        self.commandStack.undo()
        self.assertEqual(self.commandStack.current(), -1)
        self.assertTrue(self.vocab.contains('送る'))
        self.assertEqual(self.vocab.get_list_name('送る'), list_name)
        self.assertEqual(self.vocab.get_known('送る'), known)
        self.assertEqual(self.vocab.get_kana('送る'), kana)

    def test_undo_redo(self):
        self.assertEqual(self.commandStack.current(), -1)
        command = AddCommand(self.vocab, 'new')
        self.commandStack.do(command)
        self.assertEqual(self.commandStack.current(), 0)
        command = DeleteCommand(self.vocab, 'new')
        self.commandStack.do(command)
        self.assertEqual(self.commandStack.current(), 1)
        self.assertTrue(self.commandStack.undoable())
        self.assertFalse(self.commandStack.redoable())
        self.commandStack.undo()
        self.assertEqual(self.commandStack.current(), 0)
        self.assertTrue(self.commandStack.undoable())
        self.assertTrue(self.commandStack.redoable())
        self.commandStack.undo()
        self.assertEqual(self.commandStack.current(), -1)
        self.assertFalse(self.commandStack.undoable())
        self.assertTrue(self.commandStack.redoable())
        self.commandStack.redo()
        self.assertTrue(self.commandStack.undoable())
        self.assertTrue(self.commandStack.redoable())
        self.commandStack.redo()
        self.assertTrue(self.commandStack.undoable())
        self.assertFalse(self.commandStack.redoable())

    def test_NewKanaCommand(self):
        self.assertEqual(self.vocab.get_kana('送る'), ['おくる'])
        command = AddKanaCommand(self.vocab, '送る', 'new')
        self.commandStack.do(command)
        self.assertTrue(self.vocab.contains('送る', 'new'))
        self.assertEqual(self.vocab.get_kana('送る'), ['おくる', 'new'])
        message = self.commandStack.undo()
        self.assertEqual(message, 'newは送るから削除した。')
        self.assertFalse(self.vocab.contains('送る', 'new'))
        self.assertEqual(self.vocab.get_kana('送る'), ['おくる'])
        message = self.commandStack.redo()
        self.assertEqual(message, 'newは送るに追加した。')
        self.assertTrue(self.vocab.contains('送る', 'new'))
        self.assertEqual(self.vocab.get_kana('送る'), ['おくる', 'new'])
        self.commandStack.undo()
        self.assertFalse(self.vocab.contains('送る', 'new'))
        self.assertEqual(self.vocab.get_kana('送る'), ['おくる'])

    def test_DeleteKanaCommand(self):
        self.assertEqual(self.vocab.get_kana('送る'), ['おくる'])
        command = AddKanaCommand(self.vocab, '送る', 'new')
        self.commandStack.do(command)
        self.assertTrue(self.vocab.contains('送る', 'new'))
        self.assertEqual(self.vocab.get_kana('送る'), ['おくる', 'new'])
        command = DeleteKanaCommand(self.vocab, '送る', 'おくる')
        self.commandStack.do(command)
        self.assertEqual(self.vocab.get_kana('送る'), ['new'])
        command = AddKanaCommand(self.vocab, '送る', 'new2')
        self.commandStack.do(command)
        self.assertTrue(self.vocab.contains('送る', 'new2'))
        self.assertEqual(self.vocab.get_kana('送る'), ['new', 'new2'])
        command = DeleteKanaCommand(self.vocab, '送る', 'new')
        self.commandStack.do(command)
        self.assertFalse(self.vocab.contains('送る', 'new'))
        self.assertEqual(self.vocab.get_kana('送る'), ['new2'])
        message = self.commandStack.undo()
        self.assertEqual(message, 'newは送るに追加した。')
        self.assertEqual(self.vocab.get_kana('送る'), ['new', 'new2'])
        self.commandStack.undo()
        self.assertEqual(self.vocab.get_kana('送る'), ['new'])
        self.commandStack.undo()
        self.assertEqual(self.vocab.get_kana('送る'), ['おくる', 'new'])
        self.commandStack.undo()
        self.assertFalse(self.commandStack.undoable())
        message = self.commandStack.redo()
        self.assertEqual(message, 'newは送るに追加した。')
        self.assertEqual(self.vocab.get_kana('送る'), ['おくる', 'new'])
        self.commandStack.redo()
        self.assertEqual(self.vocab.get_kana('送る'), ['new'])
        self.commandStack.redo()
        self.assertEqual(self.vocab.get_kana('送る'), ['new', 'new2'])
        self.commandStack.redo()
        self.assertEqual(self.vocab.get_kana('送る'), ['new2'])
        self.assertFalse(self.commandStack.redoable())
        self.commandStack.undo()
        self.commandStack.undo()
        self.commandStack.undo()
        self.commandStack.undo()
        self.assertFalse(self.commandStack.undoable())
        self.assertEqual(self.vocab.get_kana('送る'), ['おくる'])

    def test_ToggleStatusCommand(self):
        known = self.vocab.get_known('送る')
        command = ToggleKnownCommand(self.vocab, '送る')
        self.commandStack.do(command)
        self.assertEqual(self.vocab.get_known('送る'), not known)
        message = self.commandStack.undo()
        self.assertEqual(message, '送るのステータスが未知に変更された。')
        self.assertEqual(self.vocab.get_known('送る'), known)
        message = self.commandStack.redo()
        self.assertEqual(message, '送るのステータスが既知(\x1b[32m✓\x1b[0m)に変更された。')
        self.assertEqual(self.vocab.get_known('送る'), not known)
        self.commandStack.undo()
        self.assertEqual(self.vocab.get_known('送る'), known)
