#!/bin/bash
set -e
cd ~/storage/shared/nevsjapanesevocab
if ps -ef | grep main.py | grep -v grep; then
    echo 'Already running.'
    sleep 2
    exit 0
fi
# This runs on Android where it cannot be +x'ed
python nevsjapanesevocab.py || read -p "Press enter to quit."
