#!/bin/bash
set -e
if [ -d ~/storage/shared/nevsjapanesevocab ]; then
    # Running in Termux.
    cd ~/storage/shared/nevsjapanesevocab
fi
if ps -ef | grep main.py | grep -v grep; then
    echo 'Already running.'
    sleep 2
    exit 0
fi
# This runs on Android where it cannot be +x'ed
export PYTHONPATH=$PWD/src
python nevsjapanesevocab.py || read -rp "Press enter to quit."
