#!/bin/bash
set -e
SCRIPT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
cd "$SCRIPT_DIR/.."
export MYPYPATH=$SCRIPT_DIR/../src:$SCRIPT_DIR/../tests
mypy --strict -- **/*.py
pylint --recursive=y .
bandit --skip B101 --quiet -- **/*.py && echo 'Bandit is happy.'
