#!/bin/bash
set -e
shopt -s globstar
SCRIPT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
cd "$SCRIPT_DIR/.."
for f in **/*.py; do
    pyupgrade --py310-plus "$f"
    isort --force-single-line-imports --profile black "$f"
    black "$f"
done
git diff
