#!/bin/bash
set -e
shopt -s globstar
SCRIPT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
cd "$SCRIPT_DIR/.."
for f in **/*.py; do
    black --skip-string-normalization "$f"
done
git diff
