#!/bin/bash
set -e
SCRIPT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
cd "$SCRIPT_DIR/../.."
scripts/translate
scripts/format
git diff --exit-code
scripts/check
scripts/test
