#!/bin/bash
set -e
SCRIPT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
cd "$SCRIPT_DIR/.."
export PYTHONPATH="$SCRIPT_DIR/..:$SCRIPT_DIR/../src:$SCRIPT_DIR/../tests"
PYTHONDEVMODE=1 coverage run --branch "$(which pytest)" -q
coverage report
coverage html
