#!/bin/bash
set -e
if ps -ef | grep 'py.* nevsjapanesevocab.py' | grep -qv grep; then
    echo 'Already running.'
    sleep 2
    exit 0
fi
if [ -d ~/nevsjapanesevocab ]; then
    # Running in Termux.
    cd ~/nevsjapanesevocab
    export PYTHONPATH="$PWD/src"
else
    # Running in Linux.
    SCRIPT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
    cd "$SCRIPT_DIR/.."
    export PYTHONPATH="$SCRIPT_DIR/../src"
fi
python nevsjapanesevocab.py || read -rp "Press enter to quit."
