#!/bin/bash
set -e
SCRIPT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
cd "$SCRIPT_DIR/.."
# shellcheck disable=SC2016
find . \( -name '*.py' -o -name '*.pot' -o -name '*.po' \) -print | \
    entr bash -c '
        reset; scripts/translate'
